# Generated by Django 4.2.8 on 2025-08-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_attachment_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="is_public",
            field=models.BooleanField(
                default=True, help_text="Whether this attachment is publicly visible"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subtask",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subtask",
            name="due_date",
            field=models.DateTimeField(
                blank=True, help_text="Due date for this subtask", null=True
            ),
        ),
        migrations.AddField(
            model_name="subtask",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["is_public"], name="tasks_attac_is_publ_377620_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["is_internal"], name="tasks_comme_is_inte_9189f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subtask",
            index=models.Index(
                fields=["due_date"], name="tasks_subta_due_dat_b5c543_idx"
            ),
        ),
    ]
