# Generated by Django 4.2.8 on 2025-08-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_attachment_is_public_comment_edited_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("TODO", "To Do"),
                    ("IN_PROGRESS", "In Progress"),
                    ("PAUSED", "Paused"),
                    ("REVIEW", "Under Review"),
                    ("DONE", "Done"),
                    ("BLOCKED", "Blocked"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="TODO",
                max_length=15,
            ),
        ),
    ]
