# Generated by Django 4.2.8 on 2025-08-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="subtask",
            name="paused_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("TODO", "To Do"),
                    ("IN_PROGRESS", "In Progress"),
                    ("PAUSED", "Paused"),
                    ("REVIEW", "Under Review"),
                    ("DONE", "Done"),
                    ("BLOCKED", "Blocked"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="TODO",
                max_length=15,
            ),
        ),
    ]
