# Generated by Django 4.2.8 on 2025-08-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_subtask_paused_at_subtask_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtask",
            name="description",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
