# Generated by Django 4.2.8 on 2025-08-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_alter_comment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="is_public",
            field=models.BooleanField(
                default=False, help_text="Whether this attachment is publicly visible"
            ),
        ),
    ]
