# Generated by Django 5.2.1 on 2025-08-12 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("USER", "User"),
                            ("MANAGER", "Manager"),
                        ],
                        default="USER",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_blocked", models.BooleanField(default=False)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_images/%Y/%m/%d/"
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                (
                    "password_reset_token",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                (
                    "password_reset_token_expiration",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "email_verification_token",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                (
                    "email_change_token",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                (
                    "email_change_token_expiration",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "indexes": [
                    models.Index(
                        fields=["username"], name="users_custo_usernam_a8ad03_idx"
                    ),
                    models.Index(fields=["email"], name="users_custo_email_c80f75_idx"),
                    models.Index(fields=["role"], name="users_custo_role_6a37b1_idx"),
                    models.Index(
                        fields=["is_active"], name="users_custo_is_acti_1b62ea_idx"
                    ),
                    models.Index(
                        fields=["is_verified"], name="users_custo_is_veri_8bba47_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="users_custo_created_f4b145_idx"
                    ),
                ],
            },
        ),
    ]
