# Generated by Django 4.2.8 on 2025-08-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_verification_token_expiration",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
